backend:
  name: github
  repo: etiterin/makishop # Ваш репозиторий
  branch: main # Ваша главная ветка
  
media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "products"
    label: "Товары"
    label_singular: "Товар"
    folder: "src/app/data/products"
    create: true
    slug: "{{id}}"
    fields:
      - {label: "ID", name: "id", widget: "number"}
      - {label: "Название", name: "name", widget: "string"}
      - {label: "Цена (например, 300 ₽)", name: "price", widget: "string"}
      - {label: "Категория", name: "category", widget: "select", options: ["sticker", "keychain", "set", "print"]}
      - {label: "Фандом", name: "fandom", widget: "select", options: ["Original", "Evangelion", "Pokemon", "Genshin Impact", "Other"], required: false}
      - {label: "Картинка", name: "image", widget: "image"}
      - {label: "Описание", name: "description", widget: "markdown"}
      - {label: "В наличии", name: "inStock", widget: "boolean", default: true}
